// Pre-trained Medical Patterns from MTS-Dialog Dataset
// Generated: 2025-09-01 19:58:35 +0000
// Total Patterns: 333
// 
// This file is generated by Scripts/train_patterns.swift
// DO NOT EDIT MANUALLY - regenerate using the training script

import Foundation

/// Pre-trained patterns for medical note generation
/// These patterns are compiled into the app and available to all users
struct PretrainedMedicalPatterns {
    
    /// All learned patterns organized by category
    static let patterns: [String: String] = [
                // assessment patterns (3 total)

                // symptoms patterns (24 total)

                // demographics patterns (152 total)

                // vitals patterns (12 total)

                // chiefComplaint patterns (17 total)

                // severity patterns (27 total)

                // timing patterns (15 total)

                // examination patterns (3 total)

                // disposition patterns (1 total)

                // medications patterns (28 total)

                // location patterns (22 total)

                // quality patterns (18 total)

                // allergies patterns (4 total)

                // onset patterns (7 total)
                "1 tab": "1 tab",
                "10 mg": "10 mg",
                "10/10": "10/10 - severe",
                "10mg": "10mg",
                "11 year old": "11-year-old patient",
                "125/75": "Blood pressure 125/75 mmHg",
                "195/83": "Blood pressure 195/83 mmHg",
                "2/10": "2/10 - mild",
                "20 mcg": "20 mcg",
                "20 mg": "20 mg",
                "22 year old": "22-year-old patient",
                "23 year old": "23-year-old patient",
                "28 year old": "28-year-old patient",
                "3/10": "3/10 - mild",
                "30 year old": "30-year-old patient",
                "33 year old": "33-year-old patient",
                "34 year old": "34-year-old patient",
                "38 year old": "38-year-old patient",
                "39 year old": "39-year-old patient",
                "4 mg": "4 mg",
                "40 mg": "40 mg",
                "41 year old": "41 year-old patient",
                "46 year old": "46-year-old patient",
                "5 mg": "5 mg",
                "5 out of 10": "5/10 - moderate",
                "5 year old": "5-year-old patient",
                "5/10": "5/10 - moderate",
                "54 year old": "54-year-old patient",
                "57 year old": "57-year old patient",
                "57 year old": "57-year-old patient",
                "6 mg": "6 mg",
                "6/10": "6/10 - moderate",
                "60 year old": "60-year-old patient",
                "62 year old": "62-year-old patient",
                "7/10": "7/10 - severe",
                "70 year old": "70-year-old patient",
                "71 year old": "71-year-old patient",
                "72 year old": "72-year-old patient",
                "74 year old": "74-year-old patient",
                "75 year old": "75-year-old patient",
                "750 mg": "750 mg",
                "8 mg": "8 mg",
                "8/10": "8/10 - severe",
                "80 tab": "80 Tab",
                "800 mg": "800 mg",
                "81 mg": "81 mg",
                "83 year old": "83-year-old patient",
                "9/10": "9/10 - severe",
                "abdominal": "abdominal region",
                "abdominal pain": "Abdominal Pain",
                "acetaminophen": "Acetaminophen",
                "aching": "aching quality",
                "acute": "acute presentation",
                "advil": "Ibuprofen (Advil)",
                "age 1": "The patient is a 1-year-old",
                "age 12": "The patient is a 12-year-old",
                "age 13": "The patient is a 13-year-old",
                "age 15": "The patient is a 15-year-old",
                "age 18": "The patient is a 18-year-old",
                "age 2": "The patient is a 2-year-old",
                "age 22": "The patient is a 22-year-old",
                "age 39": "The patient is a 39-year-old",
                "age 4": "The patient is a 4-year-old",
                "age 45": "The patient is a 45-year-old",
                "age 46": "The patient is a 46-year-old",
                "age 47": "The patient is a 47-year-old",
                "age 50": "The patient is a 50-year-old",
                "age 54": "The patient is a 54-year-old",
                "age 55": "The patient is a 55-year-old",
                "age 56": "The patient is a 56-year-old",
                "age 57": "The patient is a 57-year old",
                "age 57": "The patient is a 57-year-old",
                "age 58": "The patient is a 58-year-old",
                "age 69": "The patient is a 69-year-old",
                "age 72": "The patient is a 72-year-old",
                "age 75": "The patient is a 75-year-old",
                "age 82": "The patient is a 82-year-old",
                "age 84": "The patient is a 84-year-old",
                "albuterol": "Albuterol",
                "all over": "generalized",
                "allergic to": "Allergy to",
                "altered mental status": "Altered Mental Status",
                "anxiety": "Anxiety",
                "arm": "upper extremity",
                "aspirin": "Aspirin",
                "back": "back region",
                "back": "dorsal region",
                "back pain": "Back Pain",
                "belly": "abdominal region",
                "blood pressure 125/75": "BP: 125/75 mmHg",
                "blood pressure 195/83": "BP: 195/83 mmHg",
                "both sides": "bilateral",
                "bp 125/75": "BP: 125/75 mmHg",
                "bp 195/83": "BP: 195/83 mmHg",
                "burning": "burning sensation",
                "chest": "chest region",
                "chest": "thoracic region",
                "chest pain": "Chest Pain",
                "chronic": "chronic condition",
                "comes and goes": "intermittent",
                "confused": "confusion",
                "constant": "continuous",
                "constant": "persistent symptoms",
                "cough": "Cough",
                "couple weeks": "2 weeks ago",
                "cp": "chest pain",
                "cramping": "crampy quality",
                "disoriented": "disorientation",
                "dizziness": "Dizziness",
                "dizzy": "dizziness",
                "dull": "dull aching",
                "electric": "electric shock-like",
                "fever": "Fever",
                "fever 100.3": "Febrile: 100.3°F",
                "fever 101.4": "Febrile: 101.4°F",
                "few months": "2-3 months",
                "follow up": "Follow-up arranged",
                "foot": "pedal region",
                "gentleman": "male patient",
                "getting better": "improving",
                "getting worse": "progressive worsening",
                "gradual onset": "insidious onset",
                "ha": "headache",
                "hand": "hand",
                "head": "cranial region",
                "headache": "Headache",
                "heart racing": "tachycardia",
                "ibuprofen": "Ibuprofen",
                "insulin": "Insulin",
                "intermittent": "intermittent symptoms",
                "lady": "female patient",
                "last month": "1 month ago",
                "last night": "overnight",
                "last week": "1 week ago",
                "last year": "1 year ago",
                "left side": "left lateral",
                "leg": "leg region",
                "leg": "lower extremity",
                "leg pain": "Leg Pain",
                "likely": "most likely",
                "lisinopril": "Lisinopril",
                "long time": "chronic duration",
                "lower back": "lumbar region",
                "metformin": "Metformin",
                "mild": "mild severity",
                "minimal": "minimal discomfort",
                "minutes ago": "few minutes ago",
                "moderate": "moderate severity",
                "motrin": "Ibuprofen (Motrin)",
                "nausea": "Nausea",
                "neck": "cervical region",
                "negative for": "Negative for",
                "no allergies": "NKDA",
                "no blood": "Denies bleeding",
                "no chest pain": "Denies chest pain",
                "no diarrhea": "Denies diarrhea",
                "no fever": "No fever",
                "no known allergies": "NKDA",
                "no known drug allergies": "NKDA",
                "no nausea": "Denies nausea",
                "no rash": "Denies rash",
                "no tenderness": "no tenderness elicited",
                "no vomiting": "Denies vomiting",
                "no weight loss": "Denies weight loss",
                "normal": "within normal limits",
                "numbness": "numbness",
                "omeprazole": "Omeprazole",
                "on and off": "intermittent",
                "on and off": "intermittent",
                "ongoing": "persistent",
                "pain": "Pain",
                "pain": "pain region",
                "pain 10/10": "Pain severity 10/10 - severe",
                "pain 2/10": "Pain severity 2/10 - mild",
                "pain 3/10": "Pain severity 3/10 - mild",
                "pain 5 out of 10": "Pain severity 5/10 - moderate",
                "pain 5/10": "Pain severity 5/10 - moderate",
                "pain 6/10": "Pain severity 6/10 - moderate",
                "pain 7/10": "Pain severity 7/10 - severe",
                "pain 8/10": "Pain severity 8/10 - severe",
                "pain 9/10": "Pain severity 9/10 - severe",
                "passed out": "syncope",
                "pressure": "pressure-like",
                "prilosec": "Prilosec",
                "probably": "probable",
                "racing heart": "palpitations",
                "radiating": "radiating pain",
                "rash": "Rash",
                "really bad": "severe",
                "recently": "recently",
                "right side": "right lateral",
                "rule out": "rule out",
                "severe": "severe intensity",
                "sharp": "sharp/stabbing quality",
                "shooting": "shooting pain",
                "shoulder": "shoulder region",
                "sob": "shortness of breath",
                "stabbing": "stabbing pain",
                "stomach": "epigastric region",
                "sudden onset": "acute onset",
                "sweating": "diaphoresis",
                "swelling": "Swelling",
                "syncope": "Syncope",
                "temp 100.3": "Temperature: 100.3°F",
                "temp 101.4": "Temperature: 101.4°F",
                "temperature 100.3": "Temp: 100.3°F",
                "temperature 101.4": "Temp: 101.4°F",
                "tender": "tenderness on palpation",
                "terrible": "severe",
                "this afternoon": "this afternoon",
                "this morning": "earlier today",
                "throbbing": "throbbing/pulsatile",
                "throwing up": "vomiting",
                "tight": "tightness",
                "tingling": "paresthesias",
                "tired": "fatigue",
                "today": "today",
                "tolerable": "tolerable discomfort",
                "tramadol": "Tramadol",
                "trouble breathing": "difficulty breathing",
                "tylenol": "Tylenol",
                "tylenol": "Acetaminophen (Tylenol)",
                "unbearable": "unbearable pain",
                "upper back": "thoracic spine",
                "vertigo": "vertigo",
                "vomiting": "Vomiting",
                "weak": "weakness",
                "weakness": "Weakness",
                "woman": "female patient",
                "worst pain": "severe pain",
                "yesterday": "1 day ago",
    ]
    
    /// Apply patterns to improve text
    static func apply(to text: String) -> String {
        var improved = text
        
        // Sort patterns by length (longest first) to avoid partial replacements
        let sortedPatterns = patterns.sorted { $0.key.count > $1.key.count }
        
        for (patternKey, replacement) in sortedPatterns {
            // Use word boundary matching for better accuracy
            let regex = try? NSRegularExpression(
                pattern: "\\b\(NSRegularExpression.escapedPattern(for: patternKey))\\b",
                options: .caseInsensitive
            )
            
            if let regex = regex {
                improved = regex.stringByReplacingMatches(
                    in: improved,
                    range: NSRange(improved.startIndex..., in: improved),
                    withTemplate: replacement
                )
            }
        }
        
        return improved
    }
    
    /// Get statistics about loaded patterns
    static var statistics: String {
        return "Using \(patterns.count) pre-trained medical patterns from MTS-Dialog dataset"
    }
}